# Generated by Django 2.1.3 on 2018-12-03 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATE_AT')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'CATEGORY',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATE_AT')),
                ('contents', models.CharField(db_column='CONTENTS', max_length=200)),
                ('start_time', models.DateTimeField(blank=True, db_column='START_TIME', null=True)),
                ('end_time', models.DateTimeField(blank=True, db_column='END_TIME', null=True)),
                ('category', models.ForeignKey(db_column='CATEGORY_ID', on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='todo-lists.Category')),
                ('user', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.PROTECT, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TODO',
                'ordering': ['-category', '-contents'],
            },
        ),
    ]
