# Generated by Django 2.1.3 on 2018-12-03 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo-lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
