# Generated by Django 2.1.3 on 2018-12-03 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo-lists', '0002_remove_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.ForeignKey(db_column='CATEGORY_ID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='todo-lists.Category'),
        ),
    ]
